import numpy as np, pandas as pd, os
from scipy.stats import kendalltau

D = r"C:\Users\srika\Downloads\eris_sperm"
ti = pd.read_csv(os.path.join(D, "train_index.csv"))
tt = pd.read_csv(os.path.join(D, "train_tracks.csv"))
xi = pd.read_csv(os.path.join(D, "test_index.csv"))
mq = pd.read_csv(os.path.join(D, "mot_queries.csv"))
ss = pd.read_csv(os.path.join(D, "sample_submission.csv"))

print("train_index", ti.shape, "test_index", xi.shape)
print("train_tracks", tt.shape, "queries", mq.shape, "ss", ss.shape)
print()
print("train videos", ti.video.nunique(), "clips", ti["clip"].nunique())
print("test  videos", xi.video.nunique(), "clips", xi["clip"].nunique())
print("clip<->video unique in train:", ti.groupby("clip").video.nunique().max())
print("frames per clip train:", ti.groupby("clip").size().describe()[["min", "50%", "max"]].to_dict())
print("frames per clip test :", xi.groupby("clip").size().describe()[["min", "50%", "max"]].to_dict())
print("t range train", ti.t.min(), ti.t.max())
print("clips per video train:", ti.groupby("video")["clip"].nunique().describe()[["min", "50%", "max"]].to_dict())
print("clip id overlap train/test:", len(set(ti["clip"]) & set(xi["clip"])))
print("video id overlap train/test:", len(set(ti.video) & set(xi.video)))
print()
print("cells per clip train:", tt.groupby("clip").size().describe()[["min", "50%", "max"]].to_dict())
print("queries per clip test:", mq.groupby("clip").size().describe()[["min", "50%", "max"]].to_dict())
print("ss ids == mq query_id:", list(ss.id) == list(mq.query_id))
print()
print("--- target distributions ---")
for c in ["vcl", "lin", "accel", "turn", "vbias"]:
    v = tt[c].values
    print(f"{c:6s} min {v.min():9.4f} p01 {np.percentile(v,1):9.4f} p50 {np.percentile(v,50):9.4f} "
          f"p99 {np.percentile(v,99):9.4f} max {v.max():9.4f} nuniq {len(np.unique(v))}")
print()
print("--- target correlations (spearman) ---")
print(tt[["vcl", "lin", "accel", "turn", "vbias"]].corr(method="spearman").round(3))
print()
print("--- degenerate value check (ties matter for kendall tau) ---")
for c in ["vcl", "lin", "accel", "turn", "vbias"]:
    v = tt[c].values
    vc = pd.Series(v).value_counts()
    print(f"{c:6s} top values: {vc.head(3).to_dict()}  frac at mode {vc.iloc[0]/len(v):.3f}")
print()
print("--- ref position distribution ---")
print("train ref_cx", tt.ref_cx.min(), tt.ref_cx.max(), "ref_cy", tt.ref_cy.min(), tt.ref_cy.max())
print("test  ref_cx", mq.ref_cx.min(), mq.ref_cx.max(), "ref_cy", mq.ref_cy.min(), mq.ref_cy.max())
print()
print("--- images ---")
tr = np.load(os.path.join(D, "train_images.npy"), mmap_mode="r")
te = np.load(os.path.join(D, "test_images.npy"), mmap_mode="r")
print("train_images", tr.shape, tr.dtype, "test_images", te.shape, te.dtype)
print("index rows match frames:", len(ti) == tr.shape[0], len(xi) == te.shape[0])
sub = np.asarray(tr[:40])
print("pixel stats first 40 frames: min", sub.min(), "max", sub.max(), "mean", sub.mean().round(2))
print()
print("--- consecutive-frame difference magnitude (is there visible motion?) ---")
c0 = ti[ti["clip"] == ti["clip"].iloc[0]].sort_values("t")
rows = c0.row.values
f = np.asarray(tr[rows]).astype(np.float32)
print("clip0 frames", f.shape)
d = np.abs(np.diff(f, axis=0)).mean(axis=(1, 2))
print("mean |frame diff| per step:", np.round(d, 3))
print("frame std:", np.round(f.std(axis=(1, 2)), 2))
print()
print("--- sample_submission content ---")
print(ss.head(3))
print("ss nunique per col:", {c: ss[c].nunique() for c in ss.columns if c != "id"})
